create_item:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          filter:
            - domain: calendar
              integration: chore_calendar
    chore_name:
      required: true
      example: "Morning Medicine"
      selector:
        text:
    description:
      example: "Take with food. Refills are in the hall closet."
      selector:
        text:
          multiline: true
    trigger_entity:
      selector:
        entity:
          filter:
            - domain: tag
    assigned_to:
      selector:
        entity:
          filter:
            - domain: person
          multiple: true
    scheduled:
      selector:
        object:
          translation_key: scheduled
          fields:
            frequency:
              required: true
              selector:
                select:
                  options:
                    - label: Daily
                      value: daily
                    - label: Weekly
                      value: weekly
                    - label: Monthly
                      value: monthly
                    - label: Yearly
                      value: yearly
            interval:
              selector:
                number:
                  min: 1
                  mode: box
            byday:
              selector:
                select:
                  multiple: true
                  mode: list
                  options:
                    - label: Monday
                      value: mon
                    - label: Tuesday
                      value: tue
                    - label: Wednesday
                      value: wed
                    - label: Thursday
                      value: thu
                    - label: Friday
                      value: fri
                    - label: Saturday
                      value: sat
                    - label: Sunday
                      value: sun
            bymonthday:
              selector:
                text:
                  multiple: true
            bysetpos:
              selector:
                text:
                  multiple: true
            bymonth:
              selector:
                select:
                  multiple: true
                  options:
                    - label: January
                      value: "1"
                    - label: February
                      value: "2"
                    - label: March
                      value: "3"
                    - label: April
                      value: "4"
                    - label: May
                      value: "5"
                    - label: June
                      value: "6"
                    - label: July
                      value: "7"
                    - label: August
                      value: "8"
                    - label: September
                      value: "9"
                    - label: October
                      value: "10"
                    - label: November
                      value: "11"
                    - label: December
                      value: "12"
            dtstart:
              selector:
                time:
            until:
              selector:
                datetime:
            count:
              selector:
                number:
                  min: 1
                  mode: box
            persist:
              selector:
                boolean:
    interval:
      selector:
        object:
          translation_key: interval
          fields:
            frequency:
              required: true
              selector:
                select:
                  options:
                    - label: Minutely
                      value: minutely
                    - label: Hourly
                      value: hourly
                    - label: Daily
                      value: daily
                    - label: Weekly
                      value: weekly
                    - label: Monthly
                      value: monthly
                    - label: Yearly
                      value: yearly
            interval:
              selector:
                number:
                  min: 1
                  mode: box
            bymonth:
              selector:
                select:
                  multiple: true
                  options:
                    - label: January
                      value: "1"
                    - label: February
                      value: "2"
                    - label: March
                      value: "3"
                    - label: April
                      value: "4"
                    - label: May
                      value: "5"
                    - label: June
                      value: "6"
                    - label: July
                      value: "7"
                    - label: August
                      value: "8"
                    - label: September
                      value: "9"
                    - label: October
                      value: "10"
                    - label: November
                      value: "11"
                    - label: December
                      value: "12"
            until:
              selector:
                datetime:
            count:
              selector:
                number:
                  min: 1
                  mode: box
            persist:
              selector:
                boolean:
    oneshot:
      selector:
        object:
          translation_key: oneshot
          fields:
            due_datetime:
              selector:
                datetime:
            persist:
              selector:
                boolean:
    pending_period:
      selector:
        duration:
    grace_period:
      selector:
        duration:

update_item:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          filter:
            - domain: calendar
              integration: chore_calendar
            - domain: sensor
              integration: chore_calendar
    item:
      selector:
        text:
    chore_name:
      selector:
        text:
    description:
      selector:
        text:
          multiline: true
    trigger_entity:
      selector:
        entity:
          filter:
            - domain: tag
    assigned_to:
      selector:
        entity:
          filter:
            - domain: person
          multiple: true
    scheduled:
      selector:
        object:
          translation_key: scheduled
          fields:
            frequency:
              selector:
                select:
                  options:
                    - label: Daily
                      value: daily
                    - label: Weekly
                      value: weekly
                    - label: Monthly
                      value: monthly
                    - label: Yearly
                      value: yearly
            interval:
              selector:
                number:
                  min: 1
                  mode: box
            byday:
              selector:
                select:
                  multiple: true
                  mode: list
                  options:
                    - label: Monday
                      value: mon
                    - label: Tuesday
                      value: tue
                    - label: Wednesday
                      value: wed
                    - label: Thursday
                      value: thu
                    - label: Friday
                      value: fri
                    - label: Saturday
                      value: sat
                    - label: Sunday
                      value: sun
            bymonthday:
              selector:
                text:
                  multiple: true
            bysetpos:
              selector:
                text:
                  multiple: true
            bymonth:
              selector:
                select:
                  multiple: true
                  options:
                    - label: January
                      value: "1"
                    - label: February
                      value: "2"
                    - label: March
                      value: "3"
                    - label: April
                      value: "4"
                    - label: May
                      value: "5"
                    - label: June
                      value: "6"
                    - label: July
                      value: "7"
                    - label: August
                      value: "8"
                    - label: September
                      value: "9"
                    - label: October
                      value: "10"
                    - label: November
                      value: "11"
                    - label: December
                      value: "12"
            dtstart:
              selector:
                time:
            until:
              selector:
                datetime:
            count:
              selector:
                number:
                  min: 1
                  mode: box
            persist:
              selector:
                boolean:
    interval:
      selector:
        object:
          translation_key: interval
          fields:
            frequency:
              selector:
                select:
                  options:
                    - label: Minutely
                      value: minutely
                    - label: Hourly
                      value: hourly
                    - label: Daily
                      value: daily
                    - label: Weekly
                      value: weekly
                    - label: Monthly
                      value: monthly
                    - label: Yearly
                      value: yearly
            interval:
              selector:
                number:
                  min: 1
                  mode: box
            bymonth:
              selector:
                select:
                  multiple: true
                  options:
                    - label: January
                      value: "1"
                    - label: February
                      value: "2"
                    - label: March
                      value: "3"
                    - label: April
                      value: "4"
                    - label: May
                      value: "5"
                    - label: June
                      value: "6"
                    - label: July
                      value: "7"
                    - label: August
                      value: "8"
                    - label: September
                      value: "9"
                    - label: October
                      value: "10"
                    - label: November
                      value: "11"
                    - label: December
                      value: "12"
            until:
              selector:
                datetime:
            count:
              selector:
                number:
                  min: 1
                  mode: box
            persist:
              selector:
                boolean:
    oneshot:
      selector:
        object:
          translation_key: oneshot
          fields:
            due_datetime:
              selector:
                datetime:
            persist:
              selector:
                boolean:
    pending_period:
      selector:
        duration:
    grace_period:
      selector:
        duration:

delete_item:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          filter:
            - domain: calendar
              integration: chore_calendar
            - domain: sensor
              integration: chore_calendar
    item:
      selector:
        text:

complete_item:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          filter:
            - domain: calendar
              integration: chore_calendar
            - domain: sensor
              integration: chore_calendar
    item:
      selector:
        text:
    completed_by:
      selector:
        entity:
          filter:
            - domain: person
    completed_at:
      selector:
        datetime:
    keep_skip:
      selector:
        boolean:

skip_item:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          filter:
            - domain: calendar
              integration: chore_calendar
            - domain: sensor
              integration: chore_calendar
    item:
      selector:
        text:
    until:
      selector:
        datetime:

uncomplete_item:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          filter:
            - domain: calendar
              integration: chore_calendar
            - domain: sensor
              integration: chore_calendar
    item:
      selector:
        text:

hide_completed_items:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          filter:
            - domain: calendar
              integration: chore_calendar
    before:
      selector:
        datetime:
    keep_for:
      selector:
        duration:

get_items:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          filter:
            - domain: calendar
              integration: chore_calendar
    status:
      selector:
        select:
          translation_key: status
          options:
            - completed
            - due
            - overdue
            - pending
