create_item:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          filter:
            - domain: calendar
              integration: chore_calendar
    chore_name:
      required: true
      example: "Morning Medicine"
      selector:
        text:
    trigger_entity:
      selector:
        entity:
          filter:
            - domain: tag
    assigned_to:
      selector:
        entity:
          filter:
            - domain: person
          multiple: true
    scheduled:
      selector:
        object:
          translation_key: scheduled
          fields:
            time:
              required: true
              selector:
                time:
            active_days:
              selector:
                select:
                  multiple: true
                  options:
                    - label: Monday
                      value: mon
                    - label: Tuesday
                      value: tue
                    - label: Wednesday
                      value: wed
                    - label: Thursday
                      value: thu
                    - label: Friday
                      value: fri
                    - label: Saturday
                      value: sat
                    - label: Sunday
                      value: sun
    interval:
      selector:
        duration:
    oneshot:
      selector:
        object:
          translation_key: oneshot
          fields:
            due_datetime:
              selector:
                datetime:
            persist:
              selector:
                boolean:
    pending_period:
      selector:
        duration:
    grace_period:
      selector:
        duration:

update_item:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          filter:
            - domain: calendar
              integration: chore_calendar
            - domain: sensor
              integration: chore_calendar
    item:
      selector:
        text:
    chore_name:
      selector:
        text:
    trigger_entity:
      selector:
        entity:
          filter:
            - domain: tag
    assigned_to:
      selector:
        entity:
          filter:
            - domain: person
          multiple: true
    scheduled:
      selector:
        object:
          translation_key: scheduled
          fields:
            time:
              selector:
                time:
            active_days:
              selector:
                select:
                  multiple: true
                  options:
                    - label: Monday
                      value: mon
                    - label: Tuesday
                      value: tue
                    - label: Wednesday
                      value: wed
                    - label: Thursday
                      value: thu
                    - label: Friday
                      value: fri
                    - label: Saturday
                      value: sat
                    - label: Sunday
                      value: sun
    interval:
      selector:
        duration:
    oneshot:
      selector:
        object:
          translation_key: oneshot
          fields:
            due_datetime:
              selector:
                datetime:
            persist:
              selector:
                boolean:
    pending_period:
      selector:
        duration:
    grace_period:
      selector:
        duration:

delete_item:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          filter:
            - domain: calendar
              integration: chore_calendar
            - domain: sensor
              integration: chore_calendar
    item:
      selector:
        text:

complete_item:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          filter:
            - domain: calendar
              integration: chore_calendar
            - domain: sensor
              integration: chore_calendar
    item:
      selector:
        text:
    completed_by:
      selector:
        entity:
          filter:
            - domain: person
    completed_at:
      selector:
        datetime:
    keep_skip:
      selector:
        boolean:

skip_item:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          filter:
            - domain: calendar
              integration: chore_calendar
            - domain: sensor
              integration: chore_calendar
    item:
      selector:
        text:
    until:
      selector:
        datetime:

uncomplete_item:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          filter:
            - domain: calendar
              integration: chore_calendar
            - domain: sensor
              integration: chore_calendar
    item:
      selector:
        text:

hide_completed_items:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          filter:
            - domain: calendar
              integration: chore_calendar
    before:
      selector:
        datetime:
    keep_for:
      selector:
        duration:

get_items:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          filter:
            - domain: calendar
              integration: chore_calendar
    status:
      selector:
        select:
          translation_key: status
          options:
            - completed
            - due
            - overdue
            - pending
